2016-09-23 19:25:34,584 AWT-EventQueue-0 ERROR utils.ApplicationException - Error al conectar a la DB
java.sql.SQLException: Access denied for user 'tp1-user'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:998) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3835) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3771) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2239) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2270) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_40]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_40]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_40]
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:389) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:399) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325) ~[mysql-connector-java-5.1.35-bin.jar:5.1.35]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_40]
	at java.sql.DriverManager.getConnection(Unknown Source) ~[?:1.8.0_40]
	at data.FactoryConexion.getConn(FactoryConexion.java:43) [bin/:?]
	at data.DataPersonaje.getAll(DataPersonaje.java:106) [bin/:?]
	at negocio.CtrlPersonaje.getPersonajes(CtrlPersonaje.java:45) [bin/:?]
	at uiDesktop.PanelPrincipal.cargarPersonajes(PanelPrincipal.java:176) [bin/:?]
	at uiDesktop.PanelPrincipal.<init>(PanelPrincipal.java:169) [bin/:?]
	at uiDesktop.TP1.initialize(TP1.java:74) [bin/:?]
	at uiDesktop.TP1.<init>(TP1.java:61) [bin/:?]
	at uiDesktop.TP1$1.run(TP1.java:48) [bin/:?]
	at java.awt.event.InvocationEvent.dispatch(Unknown Source) [?:1.8.0_40]
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source) [?:1.8.0_40]
	at java.awt.EventQueue.access$500(Unknown Source) [?:1.8.0_40]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_40]
	at java.awt.EventQueue$3.run(Unknown Source) [?:1.8.0_40]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_40]
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source) [?:1.8.0_40]
	at java.awt.EventQueue.dispatchEvent(Unknown Source) [?:1.8.0_40]
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source) [?:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source) [?:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source) [?:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_40]
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source) [?:1.8.0_40]
	at java.awt.EventDispatchThread.run(Unknown Source) [?:1.8.0_40]
